# Setting up
----------------------

##  How to add your Conda environment to your jupyter notebook

- conda create --name your_env_name
- conda install -c anaconda ipykernel
- python -m ipykernel install --user --name=your_env_name

https://medium.com/@nrk25693/how-to-add-your-conda-environment-to-your-jupyter-notebook-in-just-4-steps-abeab8b8d084

# Install Graphlab in Conda env:

- The pip command needs to be modified to "pip2.7"
- https://turi.com/download/install-graphlab-create-command-line.html
- When configuring ipykernel use "python2.7" instead of "python"

# Download and install Turi Create official
- https://github.com/apple/turicreate#installation
- Turi Create user guide https://apple.github.io/turicreate/docs/userguide/
- Turi Create API documentation https://apple.github.io/turicreate/docs/api/

--------------------------

# very basics exercises

In [1]:
import pandas as pd

In [7]:
df=pd.read_csv("./input/people-example.csv")

- column with full name

In [14]:
df["Full Name"]=df["First Name"]+" "+df["Last Name"]

In [13]:
df.head()

  First Name Last Name        Country  age       Full Name
0        Bob     Smith  United States   24       Bob Smith
1      Alice  Williams         Canada   23  Alice Williams
2    Malcolm      Jone        England   22    Malcolm Jone
3      Felix     Brown            USA   23     Felix Brown
4       Alex    Cooper         Poland   23     Alex Cooper

- add 2 to age

In [18]:
df.age= df.age+2

In [19]:
df.head()

  First Name Last Name        Country  age       Full Name
0        Bob     Smith  United States   26       Bob Smith
1      Alice  Williams         Canada   25  Alice Williams
2    Malcolm      Jone        England   24    Malcolm Jone
3      Felix     Brown            USA   25     Felix Brown
4       Alex    Cooper         Poland   25     Alex Cooper

- ussing APPLY to standarize eeuu names

In [23]:
df.Country.value_counts()

United States    2
USA              1
England          1
Switzerland      1
Canada           1
Poland           1
Name: Country, dtype: int64

In [24]:
def transform(country):
    if country == "USA":
        return "United States"
    else:
        return country

In [27]:
df.Country = df.Country.apply(transform)

# Graphlab basics

In [1]:
import graphlab

In [3]:
sales = graphlab.SFrame('../input/home_data.sframe')

This non-commercial license of GraphLab Create for academic use is assigned to a.vargas.pina@gmail.com and will expire on June 05, 2021.

[INFO] graphlab.cython.cy_server: GraphLab Create v2.1 started. Logging: /tmp/graphlab_server_1591687751.log

In [9]:
sales

Columns:
	id	str
	date	datetime
	price	float
	bedrooms	float
	bathrooms	float
	sqft_living	float
	sqft_lot	float
	floors	float
	waterfront	int
	view	int
	condition	int
	grade	float
	sqft_above	float
	sqft_basement	float
	yr_built	float
	yr_renovated	float
	zipcode	str
	lat	float
	long	float
	sqft_living15	float
	sqft_lot15	float

Rows: 21613

Data:
+------------+---------------------------+-----------+----------+-----------+
|     id     |            date           |   price   | bedrooms | bathrooms |
+------------+---------------------------+-----------+----------+-----------+
| 7129300520 | 2014-10-13 00:00:00+00:00 |  221900.0 |   3.0    |    1.0    |
| 6414100192 | 2014-12-09 00:00:00+00:00 |  538000.0 |   3.0    |    2.25   |
| 5631500400 | 2015-02-25 00:00:00+00:00 |  180000.0 |   2.0    |    1.0    |
| 2487200875 | 2014-12-09 00:00:00+00:00 |  604000.0 |   4.0    |    3.0    |
| 1954400510 | 2015-02-18 00:00:00+00:00 |  510000.0 |   3.0    |    2.0    |
| 7237550310 | 2014-05-12 00:00:00+00:00 | 1225000.0 |   4.0    |    4.5    |
| 1321400060 | 2014-06-27 00:00:00+00:00 |  257500.0 |   3.0    |    2.25   |
| 2008000270 | 2015-01-15 00:00:00+00:00 |  291850.0 |   3.0    |    1.5    |
| 2414600126 | 2015-04-15 00:00:00+00:00 |  229500.0 |   3.0    |    1.0    |
| 3793500160 | 2015-03-12 00:00:00+00:00 |  323000.0 |   3.0    |    2.5    |
+------------+---------------------------+-----------+----------+-----------+
+-------------+----------+--------+------------+------+-----------+-------+
| sqft_living | sqft_lot | floors | waterfront | view | condition | grade |
+-------------+----------+--------+------------+------+-----------+-------+
|    1180.0   |  5650.0  |  1.0   |     0      |  0   |     3     |  7.0  |
|    2570.0   |  7242.0  |  2.0   |     0      |  0   |     3     |  7.0  |
|    770.0    | 10000.0  |  1.0   |     0      |  0   |     3     |  6.0  |
|    1960.0   |  5000.0  |  1.0   |     0      |  0   |     5     |  7.0  |
|    1680.0   |  8080.0  |  1.0   |     0      |  0   |     3     |  8.0  |
|    5420.0   | 101930.0 |  1.0   |     0      |  0   |     3     |  11.0 |
|    1715.0   |  6819.0  |  2.0   |     0      |  0   |     3     |  7.0  |
|    1060.0   |  9711.0  |  1.0   |     0      |  0   |     3     |  7.0  |
|    1780.0   |  7470.0  |  1.0   |     0      |  0   |     3     |  7.0  |
|    1890.0   |  6560.0  |  2.0   |     0      |  0   |     3     |  7.0  |
+-------------+----------+--------+------------+------+-----------+-------+
+------------+---------------+----------+--------------+---------+-------------+
| sqft_above | sqft_basement | yr_built | yr_renovated | zipcode |     lat     |
+------------+---------------+----------+--------------+---------+-------------+
|   1180.0   |      0.0      |  1955.0  |     0.0      |  98178  | 47.51123398 |
|   2170.0   |     400.0     |  1951.0  |    1991.0    |  98125  | 47.72102274 |
|   770.0    |      0.0      |  1933.0  |     0.0      |  98028  | 47.73792661 |
|   1050.0   |     910.0     |  1965.0  |     0.0      |  98136  |   47.52082  |
|   1680.0   |      0.0      |  1987.0  |     0.0      |  98074  | 47.61681228 |
|   3890.0   |     1530.0    |  2001.0  |     0.0      |  98053  | 47.65611835 |
|   1715.0   |      0.0      |  1995.0  |     0.0      |  98003  | 47.30972002 |
|   1060.0   |      0.0      |  1963.0  |     0.0      |  98198  | 47.40949984 |
|   1050.0   |     730.0     |  1960.0  |     0.0      |  98146  | 47.51229381 |
|   1890.0   |      0.0      |  2003.0  |     0.0      |  98038  | 47.36840673 |
+------------+---------------+----------+--------------+---------+-------------+
+---------------+---------------+-----+
|      long     | sqft_living15 | ... |
+---------------+---------------+-----+
| -122.25677536 |     1340.0    | ... |
|  -122.3188624 |     1690.0    | ... |
| -122.23319601 |     2720.0    | ... |
| -122.39318505 |     1360.0    | ... |
| -122.04490059 |     1800.0    | ... |
| -122.00528655 |     4760.0    | ... |
| -122.32704857 |     2238.0    | ... |
| -122.31457273 |     1650.0    | ... |
| -122.33659507 |     1780.0    | ... |
|  -122.0308176 |     2390.0    | ... |
+---------------+---------------+-----+
[21613 rows x 21 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

# Grahplab plots

In [16]:
# plots with graphlab
#graphlab.canvas.set_target("ipynb") # if we want to avoid plotting in a different window
sales.show(view="Scatter Plot", x="sqft_living", y="price")